# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'it'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Worker\TestDtcQueueWorker:
        # public: false is possible if you completely use DependencyInjection for access to the service
        public: true
        tags:
            - { name: "dtc_queue.worker" }

    admin.client:
        class: App\Admin\ClientAdmin
        arguments: [~, App\Entity\Client, App\Controller\ClientAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Client }
        public: true

    sonata.block.service.mioblock:
        #class: Sonata\BlockBundle\Block\Service\RssBlockService
        class: App\Block\MioBlockService
        arguments:
            - ~
            - '@twig'
        tags:
            - { name: sonata.block }