api_platform:
    title: 'Iupiter Api System'
    description: 'Api system for Yocabè - Iupiter project V5.0'
    version: 1.0.0
    doctrine:
        enabled: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
