sonata_admin:
  title:      false
  title_logo: /images/logo.png
  assets:
    extra_stylesheets:
        - bundles/sonatatranslation/css/sonata-translation.css
  dashboard:
    blocks:
      -
        position: left
        type: sonata.admin.block.admin_list
        settings:
          groups: [system_group, general_group]
      -
        position: right
        type: sonata.admin.block.admin_list
        settings:
          groups: [services_group]
    groups:
      system_group:
        label: System
        items:
          - sonata.user.admin.group
          - sonata.user.admin.user

      general_group:
        label: Dati base
        items:
          - admin.client

      services_group:
        label: Servizi aggiuntivi
        items:
          - route: dtc_queue_queue_status
            label: DtcQueue


sonata_block:
  blocks:
    # enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts: [admin]

