sonata_admin:
  title:      false
  title_logo: /images/logo.png
  templates:
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'
  dashboard:
    blocks:
      -
        position: top
        class: col-md-4
        type: sonata.admin.block.admin_list
        settings:
          groups: [system_group]
      -
        position: top
        class: col-md-4
        type: sonata.admin.block.admin_list
        settings:
          groups: [general_group]
      -
        position: top
        class: col-md-4
        type: sonata.admin.block.admin_list
        settings:
          groups: [services_group]
      
      -
        position: left
        class: col-md-4
        type: sonata.block.service.testo
        settings:
            content: >
                <h2>Welcome to the Sonata Admin</h2>
                <p>This is a <code>sonata.block.service.text</code> from the Block
                Bundle, you can create and add new block in these area by configuring
                the <code>sonata_admin</code> section.</p> <br/> For instance, here
                a RSS feed parser (<code>sonata.block.service.rss</code>):

      -
        position: center
        class: col-md-6
        type: sonata.block.service.rss
        roles: []
        settings:
            title: Sonata Project's Feeds
            url: https://sonata-project.org/blog/archive.rss
                                    
    groups:
      system_group:
        label: System
        items:
          - sonata.user.admin.group
          - sonata.user.admin.user

      general_group:
        label: Dati base
        items:
          - admin.client

      services_group:
        label: Servizi aggiuntivi
        items:
          - route: dtc_queue_queue_status
            label: DtcQueue



